### ISSUE TITLE
Server port

### ISSUE THREAD

**Issue by gfurri20** [JacopoWolf/PotatoChatProtocol#12]
We have to decide what port to assign to the server.
I propose <<53 101>>: "5e" in ASCII

**Comment by Alessio789** [comment]
I think that 53101 is a great idea. In any case, one port is as good as another, as long as it is over 41,000.

**Comment by JacopoWolf** [comment]
we should maybe consider using more than one port, we might never know it might be already occupied.
But maybe I'm overthinking...?

**Comment by gfurri20** [comment]
No it's right, a dynamic port could be occupied. I don't know if exist a method which assign a port directly; another idea is to choose a small range of ports and use one of those by checking availability

**Comment by JacopoWolf** [comment]
Then i propose to use the range from **53101** to **53103** (inclusive, obv)
3 ports should be enough.
We should update [the documentation](https://github.com/JacopoWolf/PotatoChatProtocol/blob/master/docs/PCP-Min.md) specifying that if the first port is not available the client should check for the next.

**Comment by JacopoWolf** [comment]
I commited those changes at bfed06a5e7eb86d978a89a3c8f7d3512dfbfd94a

And also added a general overview, which was necessary.
