### ISSUE TITLE
invalid field types

### ISSUE THREAD

**Issue by JacopoWolf** [JacopoWolf/PotatoChatProtocol#13]
I've looked through all of the packet classes... I think some properties are of the wrong type.
especially in @Alessio789 's classes.
- i think the assigned Id could be considered as an int or as a byte[], since it's a numeral, I don't see why it should be of type string. That's thoughout all of the classes.
- json content in the PCPgroupUserList class can be a Collection<String> or an ArrayList<String> and operate the json string conversion while converting the package, or even creating a method, like jsonStringContent()

**Comment by Alessio789** [comment]
Ok, in fact if the ID is only numeric it is right to consider it as an int. For string conversion of JSON content I think it is better to do a method. I will immediately change.

**Comment by Alessio789** [comment]
I have seen that in the other classes the ID has already been implemented as byte[]. I'll use that too.
