### ISSUE TITLE
From ArrayList<Obj> to Json

### ISSUE THREAD

**Issue by gfurri20** [JacopoWolf/PotatoChatProtocol#19]
I'm thinking how to convert our `ArrayList<String> listOfUSers` in json format.
If I would use an external library ([GSON](https://sites.google.com/site/gson/gson-user-guide)), how can i do?

**Comment by JacopoWolf** [comment]
We simply add the dependency to the **pom.xml** file.

**Comment by gfurri20** [comment]
Perfect, thank you!

**Comment by JacopoWolf** [comment]
yeah and i think the library you found is a pretty good one. GJ
( leaving this here for later use )
```xml
<dependency>
  <groupId>com.google.code.gson</groupId>
  <artifactId>gson</artifactId>
  <version>2.8.6</version>
</dependency>

```
