### ISSUE TITLE
Possible code refractoring to allow future expansions

### ISSUE THREAD

**Issue by JacopoWolf** [JacopoWolf/PotatoChatProtocol#22]
should we maybe refractor the code to allow future expansions of the protocol? 
maybe by moving all packets to a Min package?

---

reference pull request is #23

**Comment by gfurri20** [comment]
Yes, i think that this is good idea

**Comment by JacopoWolf** [comment]
I propose the following:
- remove _PCP_ and _Packet_ from common packets names ( for example `PCPRegistrationPacket` to  `Registration`)
bacause it's obviusly a PCP class and we wanted it to be an abstraction on packets.
- leave important classes with the PCP preamble, like `PCPMessage` or `PCPVaribleLenght`
