### ISSUE TITLE
create tests for PCPMinInterpreter and IPCPManager

### ISSUE THREAD

**Issue by JacopoWolf** [JacopoWolf/PotatoChatProtocol#31]
I propose tests for the interpreter could go in the same test classes of their respective PCPdata, as some sort of reverse engineering test.

Middlewere tests i think are gonna be the real complicated ones.

- [x] middlewere
- [x] interpreter

**Comment by JacopoWolf** [comment]
test for the middlewere is half completed, but it should work pretty well as of now.

**Comment by gfurri20** [comment]
Regard PCPMinInterpreter tests we have completed only the Registration test.
