### ISSUE TITLE
Implement method to interpret every PCP data packet

### ISSUE THREAD

**Issue by gfurri20** [JacopoWolf/PotatoChatProtocol#36]
- [x]  Registration

- [x]  Disconnection

- [x] Alias change

- [x] Group users list RRQ

- [x] Message user to group

- [x] Message user to user

- [x] error

**Comment by gfurri20** [comment]
Every byte array have to be interpreted correctly into `IPCPData` format

**Comment by JacopoWolf** [comment]
As of now, how many are still to be implemented?

**Comment by Alessio789** [comment]
UserToGroup and UserToUser have yet to be implemented (those that can be greater than 2048)

**Comment by JacopoWolf** [comment]
Alright. Message me if you need any help with those.

**Comment by gfurri20** [comment]
Should the error message be interpreted according to you?

**Comment by JacopoWolf** [comment]
I think it should be implemented too

**Comment by gfurri20** [comment]
I wrote the last two even though I'm not sure if they work without bugs, in the next few days we run the tests
