### ISSUE TITLE
implement server-side core logic

### ISSUE THREAD

**Issue by JacopoWolf** [JacopoWolf/PotatoChatProtocol#42]

**Comment by JacopoWolf** [comment]
couple of notes:
- server should log everything it recieves.
- while writing code, more comments should be added to ensure readability by others.
- i noticed **UserListRequest** uses an **ArrayList** as a parameter. Is this specification really necessary? I don't think so. **Collection** should be used instead. It's more generic and simplifies usage.

**Comment by Alessio789** [comment]
The manager returns a collection as list of users, so I think that, for consistency, even GroupUsersList should use a collection.
