### ISSUE TITLE
NullPointerException on get aliases by room

### ISSUE THREAD

**Issue by gfurri20** [JacopoWolf/PotatoChatProtocol#75]
**version**
PCP-Min.b.3

**Describe the bug**
The method is executed even if the user list is empty.

**Expected behavior**
The method `getAliasesByRoom()` must control the number of users before proceeding.

**Comment by gfurri20** [comment]
We can insert a control if construct, if the list is empty it returns an empty collection.

**Comment by JacopoWolf** [comment]
To solve thia bug further testing must be performed first, to identify the cause.

**Comment by gfurri20** [comment]
I have verified through some tests that the error derives from the fact that the clients not connected to any topic sent a message user to chat.
The list of users was absent so the call attempt caused the error.
I solved this by inserting a control in the core on the UserToGroup package management.

**Comment by JacopoWolf** [comment]
Good job!
But I think the default behaviour should be sending a **200 chat denied** error.
